"""Codegen: extract column names from features.parquet → polybot/lib/_base_cols.py.

Context: expr_eval_v1.validate() needs a frozenset of valid base column names to
         reject typos in expr atoms. On dev, this could read parquet schema directly,
         but VPS has no parquet (scratch/ never deployed). Previously we had a hand-
         maintained `_FALLBACK_BASE_COLS` which silently drifted as ACTIVE grew.
         This script makes parquet the single source of truth and generates a Python
         module that ships with deploy.
Source:  /home/polymarket_work/scratch/data/features.parquet (mining SSOT)
Expected: Writes polybot/lib/_base_cols.py with `BASE_COLS = frozenset({...})`.
         Idempotent: re-running produces byte-identical output for the same parquet.

Run:    cd /home/polymarket_work && uv run python scratch/tools/gen_base_cols.py
        (Must run after each mining cycle that adds new features, before deploy.)
"""
from __future__ import annotations
from pathlib import Path

import pyarrow.parquet as pq

FEATURES_PARQUET = Path('/home/polymarket_work/scratch/data/features.parquet')
OUTPUT_FILE      = Path('/home/polymarket_work/polybot/lib/_base_cols.py')
META_COLS = frozenset({'cid', 'cs', 'era', 'up_won'})


def main():
    cols = sorted(set(pq.read_schema(str(FEATURES_PARQUET)).names) - META_COLS)
    src = '\n'.join(f'    {c!r},' for c in cols)

    content = f'''"""AUTO-GENERATED by scratch/tools/gen_base_cols.py — DO NOT EDIT BY HAND.

BASE_COLS = sorted frozenset of valid expr atom names, derived from
features.parquet schema (minus meta cols cid/cs/era/up_won).

Re-generate after each mining cycle: `uv run python scratch/tools/gen_base_cols.py`.
"""
BASE_COLS = frozenset({{
{src}
}})
'''
    OUTPUT_FILE.write_text(content)
    print(f"wrote {OUTPUT_FILE} ({len(cols)} cols)")


if __name__ == '__main__':
    main()
